### ISSUE TITLE
Source is not allowed. Given path

### ISSUE THREAD

**Issue by wmiriye** [rolandstarke/laravel-thumbnail#13]
Source is not allowed. Given path error given when trying to generate thumbnail.

src="{{\Thumbnail::src(storage_path('public/'.$pnews->primary_img)) }}"

**Comment by rolandstarke** [comment]
I did not test it, but the storage_path should be allowed in the default config here: https://github.com/rolandstarke/laravel-thumbnail/blob/master/config/thumbnail.php#L30

Else idk if its just for the question, but you need `->url()` to output the url.

```php
\Thumbnail::src(storage_path('public/'.$pnews->primary_img))->url()

```

**Comment by fxcjahid** [comment]
@rolandstarke  
Can you give me a solution what is the problem here?

 Method 1: 
`return \Thumbnail::src('3IKY0qvtjCyPIpruhiDYany3oLF5aCHTD5OZGuon.webp', 'pd')->url();`
 
getting error: 
>
>Source is not allowed. Given path "3IKY0qvtjCyPIpruhiDYany3oLF5aCHTD5OZGuon.webp" on disk "pd" (View: *.balde.phpp)
>

Method 2: 
`return Thumbnail::src('3IKY0qvtjCyPIpruhiDYany3oLF5aCHTD5OZGuon.webp', 'public_storage')->url();`

getting error:
>
>Using $this when not in object context (View: *.balde.php )
>

**Comment by rolandstarke** [comment]
@fxcjahid 

Hey, i think what you want is

return Thumbnail::src('3IKY0qvtjCyPIpruhiDYany3oLF5aCHTD5OZGuon.webp', 'public')->url();

**Comment by fxcjahid** [comment]
not worked anything

**Comment by rolandstarke** [comment]
How do you store the file?
